version: '3.7'

services:
    postgres:
        hostname: postgres.githubrepositoryanalyzer.local
        container_name: githubrepositoryanalyzer.postgres
        image: postgres:15.3-alpine
        ports:
            - "5434:5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: GITHUBREPOSITORYANALYZER
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        volumes:
            - ./postgresdata:/var/lib/postgresql/data
    
    rabbitmq:
        hostname: rabbitmq.githubrepositoryanalyzer.local
        container_name: githubrepositoryanalyzer.rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    redis:
        image: "redis:latest"
        ports:
        - "5002:6379"

networks: 
  default: 
    name: githubrepositoryanalyzer.local